### ISSUE TITLE
Error using read_cifti with pscalar file

### ISSUE THREAD

**Issue by AndrewPoppe** [muschellij2/cifti#2]
I am having trouble reading a pscalar.nii file using `read_cifti`.

I get an error like the following:

    Error in attributes(x) = a : attributes must be a list or NULL

I have traced the issue to the `parce_parcel` function, specifically to a `mapply` call:

    verts = mapply(function(x, a) {
                    attributes(x) = a
                    return(x)
    }, verts, vert_attr, SIMPLIFY = FALSE)

When that function is called, `verts` is a list with one element. That element is an array with 783 elements in this case (it represents the vertices associated with the first parcel, I assume). `vert_attr` is also a list with one element, a string representing the parcel label (in this case "R_V1_ROI"). 

    > vert_attr
    [[1]]
    [1] "R_V1_ROI"

Even if I were to try to manually set the attribute like this:

    attributes(verts[[1]]) <- vert_attr

it produces this error: `Error in attributes(verts[[1]]) <- vert_attr : attributes must be named`

because an earlier line in the `get_verts` function stripped the vert_attr of its name. That line is:

    vert_attr = as.list(vert_attr[[1]])

I think this is because the result of `vert_attr = xml_attrs(node)` is:

    > vert_attr
          Name 
    "R_V1_ROI"  

If I just do `as.list` then it becomes:

    > as.list(vert_attr)
    $Name
    [1] "R_V1_ROI"

which works fine in this call:

    attributes(verts[[1]]) <- vert_attr

____

Sorry if this issue is convoluted!

**Comment by muschellij2** [comment]
Can you upload the pscalar.nii?

John

**Comment by AndrewPoppe** [comment]
It wouldn't let me upload the pscalar file as is, but it let me after I gzipped it. 

[TESTER.pscalar.nii.gz](https://github.com/muschellij2/cifti/files/1568789/TESTER.pscalar.nii.gz)

**Comment by muschellij2** [comment]
Issue should be fixed in GH version:
devtools::install_github("muschellij2/cifti")
x = read_cifti("TESTER.pscalar.nii.gz
<https://github.com/muschellij2/cifti/files/1568789/TESTER.pscalar.nii.gz>")

John

**Comment by AndrewPoppe** [comment]
Great, this seems to work well.

I was wondering if there is an easy way to create a brain model from parcellated data. I'd like to visualize parcellated data on a surface, but reading the pscalar file does not produce a brain model (nor does it correctly read brain structures for me).

Thanks,
Andrew

**Comment by muschellij2** [comment]
Sorry - this project is in beta (hence the 0 designation on the version).  I don't have time at the moment to look into any of this.

**Comment by AndrewPoppe** [comment]
Ok, no problem! Maybe I'll look into it.
