### ISSUE TITLE
Distinguishing dimensions for asymmetric matrices

### ISSUE THREAD

**Issue by ToeKneeFan** [muschellij2/cifti#6]
Really love this package, thanks for creating it. Does it currently allowing reading and distinguishing the parcel labels of different dimensions for asymmetric pconn.nii files (permitted in the CIFTI specification)? This would correspond to the ALONG_ROW and ALONG_COLUMN map type fields from `wb_command -file-information`.

**Comment by muschellij2** [comment]
I don't really support this package much these days, but can you send me a
pconn.nii and I can see if I can get you what you need?
Best,
John

**Comment by ToeKneeFan** [comment]
I've sent an email with an example. Thank you again for your help.

**Comment by muschellij2** [comment]
I don't know what you want out.  I don't have the workbench, so `This would correspond to the ALONG_ROW and ALONG_COLUMN map type fields from wb_command -file-information.` doesn't mean anything to me.

**Comment by muschellij2** [comment]
Try to reinstall and use https://github.com/muschellij2/cifti/commit/109ad9eaeb117421e1fdc5c605931c41c5f2f9cb

**Comment by ToeKneeFan** [comment]
Apologies, I should have been more explicit.

I just tried out 109ad9e. It looks great! The elements of `Parcel` in the `cifti` object distinguishes between the row and column labels for pconn files now.
